### ISSUE TITLE
Description not sending

### ISSUE THREAD

**Issue by RandomModderJDK** [aimok04/iserv_exercise_discord_webhook#2]
The description cant be sent, because the selectors aren't right anymore. 
**_But I have tried to find a solution:_**
Replace line 56 in IServClient.js with `obj.description = $(".panel:first").find("div:first").find(".col-md-6:first").find("div:first").find("div:first").find(".text-break-word").text();`

**PS: Thanks for your fast response.**

**Comment by aimok04** [comment]
Oh sorry, I must have been really tired to overlook that :o
